/**
 * Old SupplyWise product slugs → today's. Until 2026-10-05 most slugs were a
 * `-copy` of some *other* product's name (`almond-slice-copy` was Amore), so the
 * clean slug cannot be derived from the old one. These are the 92 product URLs
 * that were submitted to Google Merchant Center, matched by SupplyWise product id.
 */
const LEGACY_PRODUCT_SLUGS: Record<string, string> = {
  'almond-slice-copy': 'amore',
  'almond-slice-copy-3': 'custard-horn',
  'apple-strudel-3-4-serves-copy': 'apple-strudel',
  'apple-strudel-large-6-8-serves-copy': 'blueberry-apple-strudel',
  'apple-strudel-medium-3-4-serves-copy': 'half-blueberry-apple-strudel',
  'baked-ricotta-cheesecake-half-serve-for-5-copy': 'baked-ricotta-cheesecake',
  'baked-ricotta-cheesecake-half-serve-for-5-copy-2':
    'blueberry-cheesecake-small',
  'baked-ricotta-slice-copy': 'blueberry-tart',
  'black-forrest-slice-copy': 'ganache-torta-slice',
  'black-forrest-torta-large-copy-2': 'chocolate-ganache-large',
  'black-forrest-torta-medium-copy': 'black-forrest-torta-large',
  'black-forrest-torta-medium-copy-2': 'chocolate-ganache-medium',
  'black-forrest-torta-small-copy': 'black-forrest-torta-medium',
  'black-forrest-torta-small-copy-2': 'chocolate-ganache-small',
  'blueberry-cheesecake-large-copy': 'chocolate-cheesecake-large',
  'blueberry-cheesecake-large-copy-2': 'mixed-fruit-cheesecake-large',
  'blueberry-cheesecake-large-copy-3': 'passionfruit-cheesecake-large',
  'blueberry-cheesecake-large-copy-4': 'strawberry-cheesecake-large',
  'blueberry-cheesecake-small-copy': 'blueberry-cheesecake-large',
  'blueberry-cheesecake-small-copy-2': 'chocolate-cheesecake-small',
  'blueberry-cheesecake-small-copy-3': 'mixed-fruit-cheesecake-small',
  'blueberry-cheesecake-small-copy-4': 'passionfruit-cheesecake-small',
  'blueberry-cheesecake-small-copy-5': 'strawberry-cheesecake-small',
  'blueberry-tart-copy': 'carrot-cake',
  'carrot-cake-copy': 'chocolate-horn',
  'cats-tongue-200g-copy': 'palmiers',
  'cats-tongue-200g-copy-2': 'meringue-biscuits',
  'chocolate-cheesecake-large-copy': 'coffee-cheesecake-large',
  'chocolate-cheesecake-small-copy': 'coffee-cheesecake-small',
  'chocolate-ganache-large-copy': 'continental-torta-large',
  'chocolate-ganache-large-copy-2': 'hazelnut-torta-large',
  'chocolate-ganache-medium-copy': 'continental-torta-medium',
  'chocolate-ganache-medium-copy-2': 'hazelnut-torta-medium',
  'chocolate-ganache-small-copy': 'continental-torta-small',
  'chocolate-horn-copy': 'chocolate-mudcake',
  'chocolate-mud-cake-copy': 'chocolate-profiterole',
  'chocolate-profiterole-copy': 'chocolate-puff',
  'chocolate-puff-copy': 'chocolate-tartlet',
  'chocolate-tartlet-copy': 'coffee-eclair',
  'coffee-eclair-copy': 'continental-eclair',
  'continental-eclair-copy': 'cheesecake-slice-blueberry',
  'continental-torta-small-copy': 'hazelnut-torta-small',
  'custard-horn-copy': 'dusted-profiterole',
  'dusted-profiterole-copy': 'eccle',
  'easter-bunny-traditional-copy': 'fruit-flan-large',
  'eccele-copy': 'florentine',
  'florentine-copy': 'frangipani',
  'frangipani-copy': 'hazelnut-caramel-brownie-slice',
  'fruit-flan-copy': 'honey-cake-log',
  'gf-blueberry-tart-copy': 'gf-choc-orange-and-almond-loaf',
  'gf-blueberry-tart-copy-2': 'gf-pear-tart',
  'gf-choc-orange-and-almond-loaf-copy': 'gf-pear-coconut-and-almond-loaf',
  'gf-pear-coconut-and-almond-loaf-copy': 'baked-ricotta-cheesecake-half',
  'hazelnut-caramel-slice-copy': 'honey-cake-slice',
  'hazelnut-torta-large-copy': 'rum-torta-large',
  'hazelnut-torta-medium-copy': 'rum-torta-medium',
  'hazelnut-torta-small-copy': 'rum-torta-small',
  'honey-cake-log-copy': 'honey-cake-round',
  'honey-cake-log-copy-2': 'black-forrest-torta-small',
  'honey-cake-slice-copy': 'medium-fruit-flan',
  'key-torta-copy': 'st-honore',
  'medium-fruit-flan-copy': 'moka-torta-slice',
  'mini-cheesecake-blueberry-copy': 'cheesecake-slice-passionfruit',
  'mini-cheesecake-passionfruit-copy': 'cheesecake-slice-strawberry',
  'mini-cheesecake-strawberry-copy': 'mini-eclair',
  'mini-eclair-copy': 'mini-fruit-flan',
  'mini-fruit-flan-copy': 'mini-heart-strudel',
  'mini-heart-strudel-copy': 'mini-maid-of-honour',
  'mini-maid-of-honour-copy': 'cheesecake-slice-chocolate',
  'mini-mousse-chocolate-copy': 'cheesecake-slice-espresso',
  'mini-mousse-espresso-copy': 'cheesecake-slice-white-chocolate',
  'mini-mousse-white-choc-copy': 'mini-profiterole',
  'mini-profiterole-copy': 'mini-sicilian-cannoli',
  'mini-profiterole-copy-2': 'gf-blueberry-tart',
  'mini-sicilian-cannoli-copy': 'half-apple-strudel',
  'mini-sicilian-cannoli-copy-2': 'paste-secche-250gr',
  'moka-slice-copy': 'puff',
  'moka-slice-copy-2': 'rum-torta-slice',
  'moka-slice-copy-3': 'black-forrest-torta-slice',
  'palmier-6-8-pieces-copy': 'mixed-shortbread',
  'palmier-6-8-pieces-copy-2': 'fans',
  'palmier-6-8-pieces-copy-3': 'cornflake-cookies',
  'palmier-6-8-pieces-copy-4': 'cheese-biscuits',
  'palmier-6-8-pieces-copy-5': 'cantucci',
  'paste-secche-250gr-copy': 'paste-secche-500gr',
  'paste-secche-250gr-copy-2': 'cats-tongues',
  'paste-secche-500gr-copy': 'paste-secche-1kg',
  'puff-copy': 'sicilian-cannoli',
  'puff-copy-2': 'strip',
  'rum-slice-copy': 'hazelnut-torta-slice',
  'strip-copy': 'toffee-profiterole',
  'toffee-profiterole-copy': 'vanilla-slice',
}

export function legacyProductSlug(slug: string): string | null {
  return LEGACY_PRODUCT_SLUGS[slug] ?? null
}
